[workspace]
members = ["csh", "circinus", "base"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = false
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.dev]
panic = "abort"
