[workspace]
members = ["csh", "circinus", "base", "stdt", "syscall"]
resolver = "2"

[profile.release]
opt-level = 0
codegen-units = 1
lto = false
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.dev]
panic = "abort"
